#!/system/bin/sh
#Setting path variables
DEVDIR=/dev/block/platform/msm_sdcc.1/by-name #block devices derectory
BAKDIR=/sdcard/Partition_backup #backups directory

#Checking parameters
case $1 in
--rmbak)
	rm -rf $BAKDIR/*
	echo "All backups are removed!"
;;
--lsbak)
	ls $BAKDIR
;;
--lsdev)
	ls $DEVDIR
;;
*)
if [[ -z "$2" || "$#" > "3" || -n "$3" && "$3" != "-n" && "$3" != "--nobak" ]]
then
	#Show info
	echo "Partition images flashing utility by Alexander Agura (Aug-21-2015)
This utility flashes chosen image file to a chosen partition. Partition will be backed up before flashing.
Usage: flash [PARTITION] [FILE] [-n|--nobak]
       -n,--nobak Skip backup creating
Usage#2: flash [option]
Options:
       --lsbak      List backups
       --rmbak      Clean up backup folder
       --lsdev      List available partitions"
else
	if [[ "$3" = "-n" || "$3" = "--nobak" ]]
	then
		#Flashing with -n or --nobak parameter
		echo "Flashing $2 to $1 without backup!
Processing..."
		dd if=$2 of=$DEVDIR/$1 || exit 2
		echo "Done!"
	else
		#Backing up partition
		echo "Backing up $1 before flashing..."
		mkdir -p $BAKDIR
		dd if=$DEVDIR/$1 of=$BAKDIR/$1-`busybox date -Iseconds`.img || exit 1
		echo "$1 saved as $BAKDIR/$1-`busybox date -Iseconds`.img"
		echo "Enter 'flash --lsbak' to list all backups or 'flash --rmbak' to clean up backup folder"
		#Flashing
		echo "Flashing $2 to $1 partition..."
		dd if=$2 of=$DEVDIR/$1 || exit 2
		echo "Done!"
	fi
fi
esac
